name: Build Go App for macOS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # 使用 macOS 构建环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: Build Go program
      run: go build -o myprogram_mac
